word_list = [
    "kangaroo", "koala", "outback", "sydney", "barbecue", "opera", "reef", "boomerang", "platypus",
    "beach", "surfing", "wallaby", "didgeridoo", "aborigine", "dingo", "desert", "brisbane", "melbourne",
    "tasmania", "wombat", "crocodile", "eucalyptus", "emirates", "quokka", "shark", "australia", "cricket",
    "football", "goldcoast", "train", "wildlife", "tropical", "penguin", "koori", "bushwalk", "sandstone", 
    "coral", "uluru", "wine", "adelaide", "hobart", "perth", "canberra", "blue", "mountains", "sunshine", 
    "yacht", "darwin", "parrot", "beetroot", "billabong", "boab", "koorie", "mallee", "emu", "outback",
    "sunburn", "quarry", "windsurf", "sturt", "ironbark", "frillneck", "lorikeet", "firebreak", "saltbush", 
    "humpy", "wilpena", "dreamtime", "trackers", "shearing", "swagman", "drover", "station", "wool", 
    "corroboree", "noonkanbah", "walkabout", "stockman", "sheepdog", "jillaroo", "riverina", "sundown", 
    "waltzing", "matilda", "sandgroper", "gidgee", "rainforest", "arid", "lake", "billabong", "tide", 
    "sunrise", "aboriginal", "tawny", "frogmouth", "possum", "rain", "storm", "river", "cave", "bushfire", 
    "flora", "fauna", "mangrove", "gorge", "outcrop", "cattle", "station", "quicksand", "didgeridoo", 
    "quartz", "cliff", "quokka", "cassowary", "anemone", "butterfly", "jellyfish", "urchin", "penguin", 
    "seagrass", "prawn", "turtle", "stingray", "rockpool", "manta", "ray", "seashell", "fish", "dolphin", 
    "coral", "barramundi", "trout", "mullet", "whiting", "snapper", "shark", "swordfish", "anglerfish", 
    "tuna", "crayfish", "octopus", "blue-ringed", "urchin", "reef", "whale", "dugong", "seaweed", "starfish", 
    "lobster", "shell", "rock", "reef", "pelican", "albatross", "cormorant", "seal", "gull", "squid", 
    "mussels", "clams", "oyster", "pearl", "tide", "ocean", "surf", "lagoon", "sand", "shore", "breakers", 
    "coral", "reef", "whale", "breach", "island", "marine", "aquatic", "outback", "nullarbor", "savanna", 
    "pinnacles", "gibber", "gibber", "rock", "desert", "gibber", "granite", "outback", "boulder", 
    "quicksand", "dust", "storm", "sturt", "waterhole", "mulga", "mallee", "spindly", "saltbush", "salt", 
    "lake", "sandstone", "gorge", "escarpment", "spinifex", "desert", "scrub", "acacia", "pindan", "wind", 
    "cane", "farm", "sorghum", "cotton", "barley", "wheat", "oats", "livestock", "beef", "dairy", 
    "livestock", "station", "rural", "tractors", "combines", "harvest", "drought", "flood", "silo", "granary", 
    "milk", "processing", "abattoir", "sheep", "station", "shearing", "pens", "wool", "fleece", "bales", 
    "cropping", "pasture", "cattle", "station", "dairy", "milk", "creek", "irrigation", "pumping", "waterhole", 
    "flood", "plain", "dam", "watercourse", "river", "red", "dust", "stockyard", "windmill", "tank", "boiling", 
    "billy", "gumtree", "wind", "surfer", "windsurf", "cyclone", "monsoon", "boiling", "billy", "beach", 
    "swell", "shack", "beachcomber", "coral", "beach", "pelican", "albatross", "waves", "surfboard", "pipeline", 
    "tides", "shell", "jellyfish", "pearl", "reef", "sharks", "dunes", "quicksand", "cove", "harbour", 
    "sailboat", "yacht", "windsurf", "beach", "outback", "station", "trail", "track", "camper", "tent", 
    "bonfire", "billy", "waterhole", "mulga", "gumtree", "sunset", "swag", "cattle", "sheep", "dog", "bull", 
    "herding", "driving", "stockman", "jillaroo", "outback", "tent", "sunburn", "quarry", "range", "forest", 
    "platypus", "stream", "outback", "outcrop", "wombat", "bandicoot", "quokka", "emus", "sheep", "station", 
    "sheepdog", "cockatoo", "blue-tongue", "lizard", "echidna", "possum", "quoll", "wallaroo", "bilby", 
    "numbat", "tasmanian", "devil", "rock", "wallaby", "dingo", "rainforest", "mangrove", "saltwater", 
    "crocodile", "bird", "wildflower", "mountain", "ridge", "forest", "lake", "gorge", "gumtree", "eucalyptus", 
    "forest", "sunburn", "beach", "sharks", "penguin", "dune", "track", "bushfire", "wallaby", "beachcomber", 
    "wave", "pipeline", "sailboat", "yacht", "outback", "wallaby", "tasmania", "gold", "mining", "quarry", 
    "nullarbor", "mallee", "acacia", "gumtree", "goldfields", "prospect", "station", "outback", "station", 
    "jillaroo", "kangaroo", "dingo", "platypus", "wallaby", "echidna", "wombat", "crocodile"
]
